# Começa com a imagem base de desenvolvimento de contêineres da Microsoft
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Você pode adicionar comandos aqui no futuro para instalar mais ferramentas
# Por exemplo: RUN apt-get update && apt-get install -y <sua-ferramenta>